server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: cuestionario
          uri: http://localhost:8081/
          predicates:
            - Path=/bff/cuestionario/**
          filters:
            - RewritePath=/bff/cuestionario(?<segment>.*), /cuestionario/public$\{segment}
        - id: solicitud
          uri: http://localhost:8082/
          predicates:
            - Path=/bff/solicitud/**
          filters:
            - RewritePath=/bff/solicitud(?<segment>.*), /solicitud/public$\{segment}
